-- ============================================================
-- ROLLBACK SCRIPT: Disable RLS on All Tables
-- Run this ONLY if you need to quickly disable RLS due to issues
-- ============================================================

-- Reference tables
ALTER TABLE countries DISABLE ROW LEVEL SECURITY;
ALTER TABLE countriesd DISABLE ROW LEVEL SECURITY;
ALTER TABLE legal_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE civil_law DISABLE ROW LEVEL SECURITY;
ALTER TABLE criminal_procedures_law DISABLE ROW LEVEL SECURITY;
ALTER TABLE personal_status_law DISABLE ROW LEVEL SECURITY;
ALTER TABLE court DISABLE ROW LEVEL SECURITY;
ALTER TABLE templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE case_options DISABLE ROW LEVEL SECURITY;

-- User metadata
ALTER TABLE user_metadata DISABLE ROW LEVEL SECURITY;

-- Tables with existing policies
ALTER TABLE consultations DISABLE ROW LEVEL SECURITY;
ALTER TABLE contract_reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE document_reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE trial_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE client_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE payment_orders DISABLE ROW LEVEL SECURITY;

-- Core data tables
ALTER TABLE cases DISABLE ROW LEVEL SECURITY;
ALTER TABLE clients_data DISABLE ROW LEVEL SECURITY;
ALTER TABLE clients DISABLE ROW LEVEL SECURITY;
ALTER TABLE clients_v2 DISABLE ROW LEVEL SECURITY;
ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE notes DISABLE ROW LEVEL SECURITY;

-- Sensitive tables
ALTER TABLE attachments DISABLE ROW LEVEL SECURITY;
ALTER TABLE reminders DISABLE ROW LEVEL SECURITY;

-- Financial tables
ALTER TABLE expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE office_expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE lawyer_fees DISABLE ROW LEVEL SECURITY;
ALTER TABLE attorneyFees DISABLE ROW LEVEL SECURITY;

-- User management tables
ALTER TABLE lawyer_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE lawyer DISABLE ROW LEVEL SECURITY;
ALTER TABLE attorney DISABLE ROW LEVEL SECURITY;
ALTER TABLE permission_profiles DISABLE ROW LEVEL SECURITY;

-- Other tables
ALTER TABLE actions DISABLE ROW LEVEL SECURITY;
ALTER TABLE related_cases DISABLE ROW LEVEL SECURITY;
ALTER TABLE case_update DISABLE ROW LEVEL SECURITY;
ALTER TABLE task_replies DISABLE ROW LEVEL SECURITY;
ALTER TABLE contract DISABLE ROW LEVEL SECURITY;
ALTER TABLE ff DISABLE ROW LEVEL SECURITY;
ALTER TABLE client_shared_documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE client_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE court_decisions DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;

-- ============================================================
-- ROLLBACK COMPLETE
-- All RLS has been disabled on all tables
-- ============================================================
